### ISSUE TITLE
could kubectl-trace be used on distributed system running on bare metal machine instead of VM/container

### ISSUE THREAD

**Issue by changchengx** [iovisor/kubectl-trace#107]

**Comment by fntlnz** [comment]
This looks like an interesting use case @changchengx - however the answer is no. This tool is specifically designed to run with kubernetes.

**Comment by fntlnz** [comment]
I'm closing this, however feel free to continue the discussion here. I suggest you to look at bpftrace directly and build your own automation based on the distributed system you want to use.
