### ISSUE TITLE
feature to create flamescope app that serves generated flamegraph

### ISSUE THREAD

**Issue by jdonnelly-apixio** [iovisor/kubectl-trace#113]
Something like this would probably build on top of the flame graph work being done for https://github.com/iovisor/kubectl-trace/issues/73, but I think it would be pretty neat to be able to generate a flame graph then serve it through a flamescope (https://github.com/Netflix/flamescope) container with a couple kubectl-trace commands.

**Comment by fntlnz** [comment]
I like this idea

**Comment by fntlnz** [comment]
There was something similar being worked here https://github.com/iovisor/kubectl-trace/pull/74

However, I didn't like the fact that kubectl trace itself would generate the final image.

**Comment by dalehamel** [comment]
We use speedscope internally at shopify, and just open output from GCS. Now that https://github.com/iovisor/kubectl-trace/pull/162 has landed, I think that this will be a more modular way to support viewing flamegraphs. You should just need to set up a shim to get the output from blob storage (currently only GCS supported, but no reason why S3 or azure storage couldn't be)
