### ISSUE TITLE
Travis CI status report

### ISSUE THREAD

**Issue by fntlnz** [iovisor/kubectl-trace#116]
All the recent PRs and master are unable to receive status report updates from Travis CI. 
This breaks our workflow because we can't rely on that information while merging PRs and creates confusion with the status checks when a new contributor comes.

I can debug this myself but I don't have the settings tab in this repository and that's all I need to check why this happens.

Travis is working correctly, the builds are triggering and finishing correctly. Only status update is not sent.

Travis dashboard: https://travis-ci.org/github/iovisor/kubectl-trace/pull_requests

**Comment by dalehamel** [comment]
We now just use github actions
