### ISSUE TITLE
Automatic krew releases

### ISSUE THREAD

**Issue by fntlnz** [iovisor/kubectl-trace#119]
Now that we are integrated with Krew, we'd love to avoid having to manually update Krew every time we release kubectl trace.

Instructions here: https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/

**Comment by dalehamel** [comment]
if it is in krew as "kubectl trace," i think that this adds even more fuel to the argument of making tracers generic, as that's where I first saw this called out

**Comment by dalehamel** [comment]
https://github.com/iovisor/kubectl-trace/issues/17#issuecomment-449594561 is the comment i refer to above

**Comment by rajatjindal** [comment]
Hi Team

thanks for the awesome plugin. I found this today while reading/learning about ebpf

I am also the author of `krew-release-bot` which automates the release process for krew based kubectl plugins.

I noticed that current release version is a `pre-release`, and I was wondering if there any plans to release v1.0.0 of this plugin soon. (if i remember correctly, the bot dont publish pre-releases).

I will be happy to open PR for adding `krew-release-bot` support to this repo once that is done. 

Many thanks
Rajat Jindal

**Comment by dalehamel** [comment]
hi @rajatjindal

@zqureshi and I are in the process of cutting v0.1.1 (per #133 ) what steps must be taken to ensure that the bot correctly releases this when it is prepared?

**Comment by dalehamel** [comment]
Ok I’ve moved us over to GitHub actions so this looks like we can hook this up for the v0.1.1 release

**Comment by dalehamel** [comment]
Looks like we just need to modify a boilerplate like https://github.com/rajatjindal/kubectl-evict-pod/blob/master/.krew.yaml and then add agithub action, which we can do on the goreleaser.yml

**Comment by rajatjindal** [comment]
Thanks for considering to use krew release bot

You could also use https://rajatjindal.com/tools/krew-release-bot-helper/ to generate template file for your plugin

Once u have the krew template file in, and github action configured, the bot should take it from there when u do a release. (It does not work for pre releases)

I will keep an eye on this ticket incase we run into any issues

**Comment by dalehamel** [comment]
Thanks @rajatjindal just a heads-up the tool is 500’ing

**Comment by rajatjindal** [comment]
Thanks for trying that out, and the heads up. I will check whats going on.

One common UX issue i have observed on that tool is that it accepts the name as e.g. "trace" instead of "kubectl-trace"

**Comment by dalehamel** [comment]
> One common UX issue i have observed on that tool is that it accepts the name as e.g. "trace" instead of "kubectl-trace"

I think this is the normal naming for kubernetes plugins? So it can be called `kubectl trace`, they chop off the `kubectl-` part don't they?

**Comment by dalehamel** [comment]
#140 up for review
