### ISSUE TITLE
RFC: Generic tracer support

### ISSUE THREAD

**Issue by dalehamel** [iovisor/kubectl-trace#125]
In #112 and #117 we are clearly seeing the desire for the ability to trace more than what bpftrace itself can provide.

These two comments give more detail:

* https://github.com/iovisor/kubectl-trace/pull/117#issuecomment-701186824 
* https://github.com/iovisor/kubectl-trace/issues/112#issuecomment-700932483

I think that most of the logic that is currently used for bpftrace to select what process to trace is easy to reuse for a variety of tracers. For instance, once we know what process to trace, we can use perf, strace, bcc tools, or even language-specific tracing tools like rbspy.

I think the key thing here will be to try and preserve the existing behavior. For example, if we add a `--tracer` flag, we should make `bpftrace` the default tracer. It may also imply we change how arguments are handled, to be more generic, and decoupled from bpftrace.

Since different tracers may output in different ways, we will also need to abstract how output is handled. For example, some tracers like bpftrace and strace can just stream to stdout, this is a good reasonable default. Other tracers like perf or tcpdump will need to create a file, and that file itself will need a generic way of being handled, such as interfacing with a generic cloud blobstore API (to work with S3, GCS, whatever) in order to store the data for analysis.

We may also want to embed post-processing steps / make them optional or configurable, as #73 and #74 indicate.

Overall, I think this a good approach to helping ensure a clean, modular design in kubectl-trace. Now that kubectl-trace is part of krew, I think it would be extra cool if it was the de factor go-to for a multitude of tracing tasks.

@fntlnz @leodido FYI, but i think we should have a call to discuss. @zqureshi will start putting a doc together for us to review together

**Comment by adelbertc** [comment]
+1 am interested in being involved as well, my co. used my BCC work in that PR to debug multiple resource leaks to great effect.

**Comment by fntlnz** [comment]
Strong :+1: on this one!

**Comment by dalehamel** [comment]
Fixed by https://github.com/iovisor/kubectl-trace/pull/161

**Comment by FingerLiu** [comment]
Which version will have this feature?
I just installed through krew, it seems  not updated.
```bash
k trace version
git commit: fd68b1c1bf614a7213c9834673eb8813c809b036
build date: 2021-07-14 02:00:06 +0800 CST
```

**Comment by FingerLiu** [comment]
when will this release
