### ISSUE TITLE
0.1.1 release

### ISSUE THREAD

**Issue by dalehamel** [iovisor/kubectl-trace#133]
It's been a year since the last release, and we are planning some changes that may be non-backwards compatible.

We'd like to ship a 0.1.1 release with the current behavior, but make the following changes first:

- Ship #132 to fix #105 
- Ship #130 
- Bump bpftrace to the latest, as in #131 (but perhaps add bcc separately?)

@zqureshi 

@fntlnz @leodido

**Comment by zqureshi** [comment]
Once #131 is merged I can update #130 to latest tag and should be good to go.

**Comment by leodido** [comment]
Ok for me +1

Can we use GitHub milestones for releases, please? 🙇 

https://github.com/iovisor/kubectl-trace/milestones

**Comment by dalehamel** [comment]
@leodido works for me, looks like the issues in there are out of date though, so we should cut a specific milestone for the next release.

This one here is to basically cut and update a proper 0.1.0 release but since it’s been about a year since the pre-release I think 0.1.1 is appropriate.

Our main goal with this release is to ensure the stable, available version doesn’t depend on floating tag references to the trace runner, so we can make changes to the trace runner without worrying about breaking old, released versions. We don’t really want to add new functionality on this release, most of the issues are just CI work and chores like version bumps

**Comment by dalehamel** [comment]
Released this as v0.1.2 due to issues publishing v0.1.1 initially to the krew index
