### ISSUE TITLE
bug: building with `go get` results in invalid binary

### ISSUE THREAD

**Issue by dalehamel** [iovisor/kubectl-trace#169]
Building as per our docs https://github.com/iovisor/kubectl-trace#source when building with `go get`, the resulting binary behaves bizarrely. This is mostly due to the lack of LDFLAGS being specified, and any variable which requires git to not be populated.

The outcome of this is that the images will have no tag, so will fail to run, and the `version` subcommand will be empty.

To fix this, we should ensure that these variables have reasonable defaults for when they are NOT specified, for instance, we can default the `version` to `master`, and the image tag to `latest`, as well as ensure we are pushing the :latest tag on pushes to master.

**Comment by dalehamel** [comment]
@leodido @fntlnz FYI

**Comment by leodido** [comment]
As discussed internally, I confirm those findings.

Also, I agree on the solution.

**Comment by dalehamel** [comment]
It looks like we SHOULD be already pushing :latest, but aren't:

https://github.com/iovisor/kubectl-trace/blob/master/Makefile#L117-L121

https://github.com/iovisor/kubectl-trace/blob/master/build/scripts/ci-release-image.sh#L28-L30

I think this is because github changed how `github.ref` works on github actions IIRC, so it may be that it never finds `master`. I think I ran into this somewhere else as well. Should be an easy fix.

**Comment by dalehamel** [comment]
https://github.com/iovisor/kubectl-trace/blob/master/Makefile#L36 we'll need to do a pass over all these variables and ensure their defaults are sane
