### ISSUE TITLE
Distribute via krew?

### ISSUE THREAD

**Issue by ahmetb** [iovisor/kubectl-trace#17]
Hi, I'm the maintainer of https://github.com/GoogleContainerTools/krew, a plugin manager for kubectl.

I would love to bring `kubectl trace` into `krew` which would help installation instructions for this tool, and would be a great to have example on Krew index which  already has over 20 plugins.

Krew is currently being donated to kubectl project through KEP process and already has around 20 plugins distributed via krew.

Happy to host this project on krew, and see https://github.com/GoogleContainerTools/krew/blob/master/docs/DEVELOPER_GUIDE.md if you're interested.

**Comment by fntlnz** [comment]
@ahmetb thanks for reaching out, of course! That would be a nice thing to have for kubectl-trace

**Comment by ahmetb** [comment]
I am curious if you’d be open to renaming this to kubectl-bpftrace as “trace” is too generic (e.g. can be distirbuted app tracing, too) and we have a naming convention to prevent name grabs in the centralized plugin repo.

**Comment by fntlnz** [comment]
I understand it can seem confusing since "trace" here means "kernel tracing" and not other things ending in tracing but that doesn't seem a strong reason to me to rename this project.

**Comment by ahmetb** [comment]
We can keep the repo name, but would you be open to installing it as kubectl-bpftrace?

**Comment by fntlnz** [comment]
Do you want to take this issue and contribute krew support @ahmetb ?

**Comment by ahmetb** [comment]
Packaging Go software for krew is pretty easy. You just need to provide your binary releases on supported platforms as part of your releases. See https://github.com/jasonrichardsmith/rbac-view/releases and https://github.com/GoogleContainerTools/krew-index/blob/master/plugins/rbac-view.yaml as an example.

**Comment by fntlnz** [comment]
Needs #9

**Comment by ahmetb** [comment]
Wanted to check if there’s still demand here. http://krew.dev is taking off and has doubled the amount of plugins out there since. If we get #9, this should be fairly trivial to do. 

P.S, congrats on your BPF book!

**Comment by fntlnz** [comment]
Oh missed this @ahmetb - sorry, we still want to go to krew but we don't want to have a different name on it. Since that seems to be a blocker for krew too we just can't be on it with this plugin.

**Comment by ahmetb** [comment]
Copying @corneliusweig to this discussion.
I am thinking we can make exceptions with respect to "using generic names" if a plugin already has an established user base and existed for a while. We're planning to make similar exceptions to plugins that are proposed to kubectl via a KEP proposal as well.

**Comment by corneliusweig** [comment]
So if there are realistic chances that this plugin will make it into `kubectl` as `kubectl debug`, I think all `kubectl` users would benefit, if it were available today via krew as `kubectl debug`.

On the other hand, if there are competing drafts for the `kubectl debug` command (I haven't followed what has been going on in that direction), then having it as the `debug` plugin in krew may not be so smart. After all, we could end up in a situation where `debug` shipped by krew is different from `kubectl debug`. So what's the status of KEPs relating to `kubectl debug`? Is there just this one, or are there different competing proposals?

**Comment by ahmetb** [comment]
I think this repo would be proposed as `kubectl trace`, which is unique enough, given there's already a user base here.

`kubectl debug` for this repo is unlikely, since there's already an active KEP for a kubectl subcommand (for a while) which is now being implemented as a plugin and soon will be distributed via krew.

**Comment by corneliusweig** [comment]
:man_facepalming: I meant `kubecl trace` all along. I'll fix my original post.

**Comment by fntlnz** [comment]
So to;dr: we are going on krew with `kubectl trace`

**Comment by leodido** [comment]
Agree going on krew keeping the actual name!
L.

**Comment by leodido** [comment]
Agree going on krew with the current name!

**Comment by ahmetb** [comment]
Yeah, the name is good. 
It would be great if you can follow up with a PR to `krew-index` repository. Feel free to DM me on twitter or @ here if you need help.

**Comment by ahmetb** [comment]
I can go ahead and port this to krew, but it would be good the maintainers of this repository do that to learn the procedure so that they can also release updates.

**Comment by fntlnz** [comment]
No worries @ahmetb we can figure it out. We are in the process of releasing 1.0, once that is done we can port to krew

**Comment by fntlnz** [comment]
Done !
