### ISSUE TITLE
FindPidByPodContainer unreliable

### ISSUE THREAD

**Issue by michaelgugino** [iovisor/kubectl-trace#174]
https://github.com/iovisor/kubectl-trace/blob/7fd30079cf6e00218d78500eb41786847df37fe4/pkg/procfs/procfs.go#L59

This code makes too many assumptions about what the file paths will look like.

Actual mount results on my cluster look like `/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod30cea2cf_1b80_4807_abad_d81453e199c5.slice/crio-a8077b08a56c0c6e33d6716557d882ac940cb09475c50372e22e84c40d0733f2.scope`

Additionally,   the following agruments get passed to the job container 
`--pod-uid=30cea2cf-1b80-4807-abad-d81453e199c5
 --container-id=cri-o://a8077b08a56c0c6e33d6716557d882ac940cb09475c50372e22e84c40d0733f2
`

We need to also trim the `cri-o://` prefix.  The pod UID seems to replace `-` with `_` so that is another issue.

This project works for me: https://github.com/yahoo/kubectl-flame/blob/master/agent/utils/process.go#L35

**Comment by dalehamel** [comment]
Hi there, we've never tested with cri-o before so thanks for flagging this. Thanks also for linking some more generic code.

**Comment by DrAuYueng** [comment]
@dalehamel If containerd is used as the CRI runtime, the mount info looks like:
```
/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod40934a46_d409_4f4a_bb8b_1ec0b0436320.slice/cri-containerd-afc114c69e71f18166abd63715398d7daa763c69a6454f71157272ab0bdca783.scope
```
and 
```
/var/lib/kubelet/pods/40934a46-d409-4f4a-bb8b-1ec0b0436320/containers/coredns/429f6a81
```

The generic code would be better like this:
```
if strings.Contains(root, podUID) && strings.Contains(root, containerID) {
					return &dname, nil
				}
```

The containerID can be either a name(**coredns**) or a uid(**afc114c69e71f18166abd63715398d7daa763c69a6454f71157272ab0bdca783**).

**Comment by DrAuYueng** [comment]
@dalehamel I submitted a PR(#207 ) to fix this, can you take a look?
