### ISSUE TITLE
does not work on clusters with Pod Security Policies

### ISSUE THREAD

**Issue by alban** [iovisor/kubectl-trace#32]
Symptoms:
- the job is created successfully
- its status stays empty (`status: {}`)
- no pods get created
- I can see the following event with `kubectl get events -n default`:

> 3s          Warning   FailedCreate   Job    Error creating: pods "kubectl-trace-603733c8-17e6-11e9-aec8-c85b763781a4-" is forbidden: unable to validate against any pod security policy: [spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]

kubectl-trace should use a specific ServiceAccount and its documentation should say how to install the ServiceAccount and its associated PSP.

**Comment by alban** [comment]
@fntlnz I think I prefer the option with a custom service account and add in the documentation how to create the ClusterRole and ClusterRoleBinding because that could be potentially different from one cluster to another. In my snippet, I use `privileged-psp` because that's the name of the PSP defined in my cluster, but it could be a different name in another cluster, or not even created.

**Comment by alban** [comment]
@fntlnz yes, that looks good! The next thing to implement could be something to get a useful error message that hints at the service account parameter when it's not working. Not sure how to detect that...

**Comment by fntlnz** [comment]
Cool, would you mind opening an issue on that to explore a bit @alban ?
