### ISSUE TITLE
Integration: Load kind images using the kind load command

### ISSUE THREAD

**Issue by fntlnz** [iovisor/kubectl-trace#60]
We use kind for integration tests against a kubernetes cluster. We now have a dirty hack to load the built images into the kind docker daemon since when we started using it kind was at a very early stage and didn't have the `load` command. Now the load command is available so we can just replace the hack with it!

Docs here
https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster

**Comment by alejandrox1** [comment]
Can I help out with this?

**Comment by alejandrox1** [comment]
opened a PR in kind, [kind#352](https://github.com/kubernetes-sigs/kind/pull/352), to make kind do as much of the work possible.

**Comment by fntlnz** [comment]
Oh yes please help ! @alejandrox1

**Comment by fntlnz** [comment]
I looked at that command and it does not seem an API exposed by kind as library but has the load logic hardcoded in the load command. :confused:

**Comment by dalehamel** [comment]
THis is now just done via a docker push
