### ISSUE TITLE
Missing header error while trying to run a trace

### ISSUE THREAD

**Issue by achanda** [iovisor/kubectl-trace#76]
I tried to run a trace on a cluster built with kops, here is what I see in trace logs
```
# kubectl-trace logs kubectl-trace-c2405ead-a4b3-11e9-890b-0232f65d1adc
if your program has maps to print, send a SIGINT using Ctrl-C, if you want to interrupt the execution send SIGINT two times
/bpftrace/include/asm_goto_workaround.h:14:10: fatal error: 'linux/types.h' file not found
```

Relevant info
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:40:24
Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:30:48
Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
# kubectl-trace version
git commit:
build date: undefined
# uname -a
Linux ip-10-65-134-126 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux
```

**Comment by leodido** [comment]
Hi @achanda thanks for opening this!

Can you provide the OS info for the node running this?

**Comment by achanda** [comment]
@leodido sorry, forgot that bit 😅 Update now.

**Comment by leodido** [comment]
Ok, thanks. Will take a look.

The target k8s cluster should be running on Linux. The client machine can be anything.

I'm not sure if it works on docker for mac to be honest (because of [this](https://github.com/iovisor/kubectl-trace/issues/14)).

If you want to share any other details (e.g, the minimal steps to recreate a similar cluster with kops would be really helpful) please do! :)

**Comment by achanda** [comment]
I ran this from a master node, so all other nodes in the cluster should have the same kernel and Linux version. We do, however, use our own custom AMI that adds a bunch of other tools on top of Kops' AMI. I can try this on a vanilla kops cluster.

**Comment by rikatz** [comment]
Same here. Running master and nodes with ubuntu 19.04.

Trying installing the build-essentials in all of them, but the error still happens. The cluster is running with Cilium correctly, so it might be some other thing.

The same happens while running against Node or Pod, as the following:

```
kubectl trace run -f opensnoop.bt pod/nginx-7c45b84548-9wl6j -a
trace 8b0e3f4d-a66b-11e9-b0f3-000c29cf9885 created

if your program has maps to print, send a SIGINT using Ctrl-C, if you want to interrupt the execution send SIGINT two times
/bpftrace/include/asm_goto_workaround.h:14:10: fatal error: 'linux/types.h' file not found
exit status 1
```

Tks

**Comment by rikatz** [comment]
So I've digging a little bit and found another error:

```
$ docker run -it --rm -v /lib/modules:/lib/modules -v /sys:/sys --privileged --pid=host --entrypoint /bin/sh quay.io/iovisor/kubectl-trace-bpftrace:latest

# bpftrace teste.bt
No error information: couldn't set RLIMIT_MEMLOCK for bpftrace. If your program is not loading, you can try "ulimit -l 8192" to fix the problem
/bpftrace/include/asm_goto_workaround.h:14:10: fatal error: 'linux/types.h' file not found
# apk add --update linux-headers
bpftrace teste.bt
definitions.h:10:3: error: unknown type name 's64'
definitions.h:11:3: error: unknown type name 'umode_t'
definitions.h:20:3: error: unknown type name 's64'
definitions.h:22:3: error: unknown type name 's64'
definitions.h:23:3: error: unknown type name 'umode_t'
```

So I've mounted the /usr/src from the host and worked fine

```
docker run -it --rm -v /lib/modules:/lib/modules -v /usr/src/:/usr/src -v /sys:/sys --privileged --pid=host  --entrypoint /bin/sh quay.io/iovisor/kubectl-trace-bpftrace:latest
```

Don't know if this is an Ubuntu issue or general one, but I'll keep digging to see if just mounting /usr/src (and putting linux-headers as a dependency to kubectl-trace) is all we need.

**Comment by rikatz** [comment]
It seems I've to force the --fetch-headers to kubectl-trace run, but it still doesn't work. 

I've recompiled kubectl-trace to force the container mount/map between host /usr/src and container's /usr/src and this did worked fine, but don't know if this is the right path to follow.

Waiting for further directions :)

**Comment by fntlnz** [comment]
@rikatz oh good catch! Can you give the output of:
```
ls -la /lib/modules/$(uname -r)
```
I'm curious to see the symlinks there. Maybe we need to change the strategy to detect headers in different distros.

**Comment by rikatz** [comment]
@fntlnz for sure!

```
 ls -la /lib/modules/$(uname -r)
total 5540
drwxr-xr-x  5 root root    4096 Jul  7 20:57 .
drwxr-xr-x  3 root root    4096 Jul  7 20:57 ..
lrwxrwxrwx  1 root root      39 Jun 24 08:09 build -> /usr/src/linux-headers-5.0.0-20-generic
drwxr-xr-x  2 root root    4096 Jun 24 08:09 initrd
drwxr-xr-x 17 root root    4096 Jul  7 20:57 kernel
-rw-r--r--  1 root root 1334328 Jul  7 20:57 modules.alias
-rw-r--r--  1 root root 1312239 Jul  7 20:57 modules.alias.bin
-rw-r--r--  1 root root    7744 Jun 24 08:09 modules.builtin
-rw-r--r--  1 root root    9784 Jul  7 20:57 modules.builtin.bin
-rw-r--r--  1 root root  597481 Jul  7 20:57 modules.dep
-rw-r--r--  1 root root  832653 Jul  7 20:57 modules.dep.bin
-rw-r--r--  1 root root     317 Jul  7 20:57 modules.devname
-rw-r--r--  1 root root  213933 Jun 24 08:09 modules.order
-rw-r--r--  1 root root     633 Jul  7 20:57 modules.softdep
-rw-r--r--  1 root root  594841 Jul  7 20:57 modules.symbols
-rw-r--r--  1 root root  724184 Jul  7 20:57 modules.symbols.bin
drwxr-xr-x  3 root root    4096 Jul  7 20:57 vdso
```

It seems that the symlink there created by Ubuntu might be an issue.

**Comment by rikatz** [comment]
Tks for the fix @fntlnz and @joestringer :)

**Comment by jdel12** [comment]
I just encountered this as well on a vanilla GKE cluster.  I haven't done any significant exploring to be clear, just bringing it up if it's a recurring issue.

`planet-express$ k version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}

planet-express$ #kubectl trace run -e 'tracepoint:block:block_rq_issue { @ = hist(args->bytes); }' pod/esclus02-es-nodeset-default-0 --fetch-headers -a -n default

planet-express$ k logs kubectl-trace-730dad7e-3654-11ea-8b16-acde48001122-r8rm2
if your program has maps to print, send a SIGINT using Ctrl-C, if you want to interrupt the execution send SIGINT two times
/bpftrace/include/asm_goto_workaround.h:14:10: fatal error: 'linux/types.h' file not found
exit status 1

planet-express$ kubectl trace version
git commit: d34d1d586b110af718aeadc9f3213c78e543a961
build date: 2019-09-19 10:00:13 -0500 CDT`

**Comment by stafot** [comment]
Also fails on `AWS EKS 1.16` with `Amazon Linux 2` OS on nodes. 
```
2020-06-07T17:16:27.304465751Z if your program has maps to print, send a SIGINT using Ctrl-C, if you want to interrupt the execution send SIGINT two times
2020-06-07T17:16:27.327396294Z /bpftrace/include/asm_goto_workaround.h:14:10: fatal error: 'linux/types.h' file not found
2020-06-07T17:16:27.330727621Z exit status 1
```

**Comment by joestringer** [comment]
@stafot I think you also need to install the `kernel-headers` package on the node to get this working on Amazon Linux 2.

**Comment by stafot** [comment]
@joestringer thanks I will let you know if this fixes the issue.

**Comment by stafot** [comment]
@joestringer Unfortunately it doesn't work.

**Comment by stafot** [comment]
For anyone in the future having the same problem on `Amazon Linux 2` the solution to run successfully `kubectl trace` is to have install on node the `kernel-devel` package. 
```
sudo  yum install kernel-devel-$(uname -r)
```
[relevant resource](https://www.linuxquestions.org/questions/linux-general-1/lib-modules-kernel-build-file-broken-701895/)

Thanks, @joestringer for the initial advice that help me to find the fix for my use case.

**Comment by fluffysquirrels** [comment]
Similarly, `sudo apt-get install linux-headers-amd64` fixed this on Debian 10.

**Comment by tuannvm** [comment]
For me it's still not working. I need to append the `--fetch-headers` to the kubectl trace command

**Comment by stafot** [comment]
@tuannvm on what node type are you running out of interest?

**Comment by FingerLiu** [comment]
Any guy had luck with CentOS?
Still not work on CentOS.
Even if after adding `--fetch-headers`.
I inspect into the init container, and found logs below.
Found something suspicious:on centos kernel version(uname -r) is  `5.15.4-1.el7.elrepo.x86_64`
but the install command is `yum install kernel-ml-headers.x86_64`

```bash
WARNING: Cannot find distro-specific headers for "CentOS Linux". Fetching generic headers.
+ BUILD_DIR=/linux-generic-5.15.4-1.el7.elrepo.x86_64
+ SOURCES_DIR=/usr/src/linux-generic-5.15.4-1.el7.elrepo.x86_64
+ [[ ! -e /usr/src/linux-generic-5.15.4-1.el7.elrepo.x86_64/.installed ]]
+ echo 'Installing kernel headers for generic kernel'
Installing kernel headers for generic kernel
+ fetch_generic_linux_sources
++ awk '-vFS=[-+]' '{ print $1 }'
++ echo 5.15.4-1.el7.elrepo.x86_64
+ kernel_version=5.15.4
++ echo 5.15.4-1.el7.elrepo.x86_64
++ awk -vFS=. '{ print $1 }'
+ major_version=5
+ [[ 5.15.4 == *.0 ]]
+ echo 'Fetching upstream kernel sources for 5.15.4.'
Fetching upstream kernel sources for 5.15.4.
+ mkdir -p /linux-generic-5.15.4-1.el7.elrepo.x86_64
+ curl -sL https://www.kernel.org/pub/linux/kernel/v5.x/linux-5.15.4.tar.gz
+ tar --strip-components=1 -xzf - -C /linux-generic-5.15.4-1.el7.elrepo.x86_64
tar: invalid magic
tar: short read
real	0m1.344s
user	0m0.035s
sys	0m0.017s
```

**Comment by FingerLiu** [comment]
I can confirm that I have already install header and devel on my node, why should I `--fetch-headers` on pod again.
