### ISSUE TITLE
Install fails with go 1.13

### ISSUE THREAD

**Issue by achanda** [iovisor/kubectl-trace#79]
I updated to go 1.13 and tried to install from master
```
16:04 $ go get -u github.com/iovisor/kubectl-trace/cmd/kubectl-trace
go: finding github.com/iovisor/kubectl-trace latest
go: github.com/iovisor/kubectl-trace/cmd/kubectl-trace imports
	github.com/iovisor/kubectl-trace/pkg/cmd imports
	github.com/iovisor/kubectl-trace/pkg/attacher imports
	k8s.io/kubernetes/pkg/kubectl/util/term imports
	github.com/docker/docker/pkg/term imports
	github.com/docker/docker/pkg/term/windows imports
	github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod:
	module declares its path as: github.com/sirupsen/logrus
	        but was required as: github.com/Sirupsen/logrus
```
Here is go info
```
16:16 $ go version
go version go1.13 darwin/amd64
```
I think it will be very useful if we could release pre-built binaries.

**Comment by fntlnz** [comment]
Thanks for reporting, will take a look

**Comment by thaJeztah** [comment]
I suspect something like https://github.com/iovisor/kubectl-trace/blob/master/go.mod#L14 may cause the issue; if it's expecting an older version of docker (before the Sirupsen ->sirupsen rename)

The trouble with Go modules is that (IIRC) `replace` rules are not inherited from the dependencies

**Comment by fntlnz** [comment]
Thanks for the hints @thaJeztah

**Comment by fntlnz** [comment]
OMG I've been trying hard to do the dependencies dance right in this project 😀

**Comment by fntlnz** [comment]
@achanda in the meanwhile we released pre-built binary versions in case you need:
https://github.com/iovisor/kubectl-trace#pre-built-binaries

**Comment by achanda** [comment]
Thanks @fntlnz!

**Comment by leogr** [comment]
Since #92 was merged, it works for me with `go version go1.13 linux/amd64`.
@achanda do you still have this issue?
