### ISSUE TITLE
Release mechanism for binary and package manager releases

### ISSUE THREAD

**Issue by leodido** [iovisor/kubectl-trace#9]
Two options come to my mind right now.

- from CI
   1. test
   2. build
   3. tag on github
   4. attach release with artifacts (ie., binaries) to such tag
- from local environment using a makefile command
   - step 2 to 4 above

**Comment by atosatto** [comment]
Would [goreleaser](https://github.com/goreleaser/goreleaser) be a good fit for this purpose?

**Comment by leodido** [comment]
Yeah Andrea, it would be a good fit!

**Comment by fntlnz** [comment]
Do you want to give it a try @atosatto ?

**Comment by ahmetb** [comment]
Package management part can be solved via krew (since it’s a go binary).

The rest can be goreleaser or travis-ci releases feature.
